services:
  - type: web
    name: auth-service
    env: docker
    plan: free
    dockerContext: InkWell.Auth
    dockerfilePath: InkWell.Auth/Dockerfile
    envVars:
      - key: ConnectionStrings__AuthDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379

  - type: web
    name: post-service
    env: docker
    plan: free
    dockerContext: InkWell.Post
    dockerfilePath: InkWell.Post/Dockerfile
    envVars:
      - key: ConnectionStrings__PostDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq

  - type: web
    name: category-service
    env: docker
    plan: free
    dockerContext: InkWell.Category
    dockerfilePath: InkWell.Category/Dockerfile
    envVars:
      - key: ConnectionStrings__CategoryDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379

  - type: web
    name: comment-service
    env: docker
    plan: free
    dockerContext: InkWell.Comment
    dockerfilePath: InkWell.Comment/Dockerfile
    envVars:
      - key: ConnectionStrings__CommentDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq

  - type: web
    name: media-service
    env: docker
    plan: free
    dockerContext: InkWell.Media
    dockerfilePath: InkWell.Media/Dockerfile
    envVars:
      - key: ConnectionStrings__MediaDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq

  - type: web
    name: newsletter-service
    env: docker
    plan: free
    dockerContext: InkWell.Newsletter
    dockerfilePath: InkWell.Newsletter/Dockerfile
    envVars:
      - key: ConnectionStrings__NewsletterDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq

  - type: web
    name: notification-service
    env: docker
    plan: free
    dockerContext: InkWell.Notification
    dockerfilePath: InkWell.Notification/Dockerfile
    envVars:
      - key: ConnectionStrings__NotificationDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq

  - type: web
    name: inkwell-gateway
    env: docker
    plan: free
    dockerContext: InkWell.Gateway
    dockerfilePath: InkWell.Gateway/Dockerfile
    envVars:
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"

databases:
  - name: inkwell-db
    databaseName: inkwell
    plan: free
