services:
  - type: web
    name: auth-service
    env: docker
    plan: free
    dockerContext: InkWell.Auth
    dockerfilePath: InkWell.Auth/Dockerfile
    buildFilter:
      paths:
        - "InkWell.Auth/**"
    envVars:
      - key: ConnectionStrings__AuthDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: Jwt__Secret
        value: FPICUVNej03KufTJmHzbToS8jMYHWXIuUkNRGxWHoAg=
      - key: Jwt__Issuer
        value: InkWell
      - key: Jwt__Audience
        value: InkWellUsers

  - type: web
    name: post-service
    env: docker
    plan: free
    dockerContext: InkWell.Post
    dockerfilePath: InkWell.Post/Dockerfile
    buildFilter:
      paths:
        - "InkWell.Post/**"
    envVars:
      - key: ConnectionStrings__PostDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq
      - key: Jwt__Secret
        value: FPICUVNej03KufTJmHzbToS8jMYHWXIuUkNRGxWHoAg=
      - key: Jwt__Issuer
        value: InkWell
      - key: Jwt__Audience
        value: InkWellUsers

  - type: web
    name: category-service
    env: docker
    plan: free
    dockerContext: InkWell.Category
    dockerfilePath: InkWell.Category/Dockerfile
    buildFilter:
      paths:
        - "InkWell.Category/**"
    envVars:
      - key: ConnectionStrings__CategoryDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: Jwt__Secret
        value: FPICUVNej03KufTJmHzbToS8jMYHWXIuUkNRGxWHoAg=
      - key: Jwt__Issuer
        value: InkWell
      - key: Jwt__Audience
        value: InkWellUsers

  - type: web
    name: comment-service
    env: docker
    plan: free
    dockerContext: InkWell.Comment
    dockerfilePath: InkWell.Comment/Dockerfile
    buildFilter:
      paths:
        - "InkWell.Comment/**"
    envVars:
      - key: ConnectionStrings__CommentDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq
      - key: Jwt__Secret
        value: FPICUVNej03KufTJmHzbToS8jMYHWXIuUkNRGxWHoAg=
      - key: Jwt__Issuer
        value: InkWell
      - key: Jwt__Audience
        value: InkWellUsers

  - type: web
    name: media-service
    env: docker
    plan: free
    dockerContext: InkWell.Media
    dockerfilePath: InkWell.Media/Dockerfile
    buildFilter:
      paths:
        - "InkWell.Media/**"
    envVars:
      - key: ConnectionStrings__MediaDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq
      - key: Jwt__Secret
        value: FPICUVNej03KufTJmHzbToS8jMYHWXIuUkNRGxWHoAg=
      - key: Jwt__Issuer
        value: InkWell
      - key: Jwt__Audience
        value: InkWellUsers

  - type: web
    name: newsletter-service
    env: docker
    plan: free
    dockerContext: InkWell.Newsletter
    dockerfilePath: InkWell.Newsletter/Dockerfile
    buildFilter:
      paths:
        - "InkWell.Newsletter/**"
        - "InkWell.Shared/**" # If shared logic exists
    envVars:
      - key: ConnectionStrings__NewsletterDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq
      - key: Jwt__Secret
        value: FPICUVNej03KufTJmHzbToS8jMYHWXIuUkNRGxWHoAg=
      - key: Jwt__Issuer
        value: InkWell
      - key: Jwt__Audience
        value: InkWellUsers

  - type: web
    name: notification-service
    env: docker
    plan: free
    dockerContext: InkWell.Notification
    dockerfilePath: InkWell.Notification/Dockerfile
    buildFilter:
      paths:
        - "InkWell.Notification/**"
    envVars:
      - key: ConnectionStrings__NotificationDB
        fromDatabase:
          name: inkwell-db
          property: connectionString
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"
      - key: Redis__ConnectionString
        value: red-d81dfsd7vvec73f0k0jg:6379
      - key: RabbitMQ__ConnectionString
        value: amqps://zpaoakqq:lFC72m-zIIRXT_kctJz8AkaSuQ5eaU0y@beaver.rmq.cloudamqp.com/zpaoakqq
      - key: Jwt__Secret
        value: FPICUVNej03KufTJmHzbToS8jMYHWXIuUkNRGxWHoAg=
      - key: Jwt__Issuer
        value: InkWell
      - key: Jwt__Audience
        value: InkWellUsers

  - type: web
    name: inkwell-gateway
    env: docker
    plan: free
    dockerContext: InkWell.Gateway
    dockerfilePath: InkWell.Gateway/Dockerfile
    buildFilter:
      includedPaths:
        - "InkWell.Gateway/**"
        - "render.yaml" # Build gateway if routing changes
    envVars:
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_gcServer
        value: "0"

databases:
  - name: inkwell-db
    databaseName: inkwell
    plan: free
